# Metadata for your course

title: Learning Godot with C#
tagline: Learning Godot with C#
description: Build a platformer game in Godot and C#

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: working-with-github-learning-lab
  repo: lab-starter-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  title: Welcome to Repository
  body: welcome-text.md
 
# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Create a new pull request
  description: Add your name to the README.md file in your new pull request
  event: pull_request.opened
  actions:
  - type: gate
    left: '%payload.pull_request.title%'  # get the title from the pull request object inside of the payload
    operator: ===                         # check for strict equality, see more at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators#Identity
    right: Add name to README             # this is the expected value
  - type: respond
    with: pr-opened.md
